# Generated by Django 6.0.7 on 2026-08-07 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Frontend', 'Frontend'), ('Backend', 'Backend'), ('Database', 'Database'), ('Tools', 'Tools')], max_length=50)),
                ('icon', models.CharField(help_text='React Icon name. Example: FaReact, SiDjango, SiMysql', max_length=100)),
                ('color', models.CharField(default='text-blue-500', help_text='Tailwind CSS class', max_length=100)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
