# Generated by Django 6.0.7 on 2026-08-07 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('start_date', models.CharField(max_length=50)),
                ('end_date', models.CharField(default='Present', max_length=50)),
                ('description', models.TextField()),
                ('technologies', models.CharField(blank=True, help_text='Comma separated e.g. React,Django,MySQL', max_length=300)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='experience/')),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
    ]
