# Generated by Django 6.0.7 on 2026-08-09 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='icon',
            field=models.CharField(default='Briefcase', max_length=30),
        ),
        migrations.AddField(
            model_name='experience',
            name='responsibilities',
            field=models.TextField(default=2, help_text='One responsibility per line'),
            preserve_default=False,
        ),
    ]
