# Generated by Django 6.0.7 on 2026-08-04 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='features',
            field=models.TextField(blank=True, help_text='Login, Payment, Dashboard'),
        ),
    ]
